apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: luf62wuvc-go 
  janus-idp.io/tekton: luf62wuvc-go
  backstage.io/kubernetes-id: luf62wuvc-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: luf62wuvc-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml